_format_version: "2.1"

services:
  - name: auth-service
    url: http://host.docker.internal:8081
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: false
        preserve_host: false

  - name: user-service
    url: http://host.docker.internal:8082
    routes:
      - name: user-route
        paths:
          - /user/v1/
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://host.docker.internal:8081/auth/v1/ping"
        enabled: true

  - name: data-extraction-service
    url: http://host.docker.internal:8083
    routes:
      - name: data-extraction-route
        paths:
          - /analyse/v1/
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://host.docker.internal:8081/auth/v1/ping"
        enabled: true

  - name: expense-service
    url: http://host.docker.internal:8084
    routes:
      - name: expense-route
        paths:
          - /expense/v1/
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://host.docker.internal:8081/auth/v1/ping"
        enabled: true
