name: Secret Detection

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  detect-secrets:
    name: Scan for Exposed Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""  # Use Gitleaks' default rules
          fail: true  # Fail workflow if secrets are found

      - name: Create GitHub Issue if Secrets Found
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "🚨 Exposed Secret Detected!",
              body: "Gitleaks has detected a potential secret in the latest commit. Please investigate immediately!",
              labels: ["security", "urgent"]
            });
