name: Trigger Secret Scan

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-secret-scan:
    uses: NifasatBeg/CashFlowDeps/.github/workflows/reusable-secrets-scan.yml@main 
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
